# Generated by Django 6.1.1 on 2026-10-05 14:19

import backend.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=backend.events.models.new_event_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('Community', 'Community'), ('Technology', 'Technology'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Food', 'Food'), ('Nature', 'Nature')], default='Community', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('PUBLISHED', 'Published')], default='PENDING_REVIEW', max_length=20)),
                ('organiser_id', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['status', 'starts_at'], name='events_even_status_5c3d55_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='event_capacity_positive'), models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_REVIEW', 'PUBLISHED'])), name='event_status_valid')],
            },
        ),
    ]
