# Generated by Django 6.1.1 on 2026-10-05 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EVENT_PUBLISHED', 'Event Published'), ('REGISTRATION_CREATED', 'Registration Created')], max_length=30)),
                ('event_id', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'activity',
                'ordering': ['-id'],
            },
        ),
    ]
