# Generated by Django 6.1.1 on 2026-10-05 14:19

import backend.registrations.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.CharField(default=backend.registrations.models.new_registration_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
        ),
    ]
